
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: shoplify_0_development

  <<: *default
  database: shoplify_0_test

production:
  <<: *default
  database: shoplify_0_production
  username: shoplify_0
  password: <%= ENV["SHOPLIFY_0_DATABASE_PASSWORD"] %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>